name: Clang Format

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]


jobs:
  clang-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          find . -maxdepth 1 \( -name "*.ino" -o -name "*.h" -o -name "*.hpp" -o -name "*.cpp" \) -print0 \
            | xargs -0 -r clang-format -i

  - name: Commit and Push changes
      run: |
        # Commit only modified
        if [ -n "$(git status --porcelain)" ]; then
          git config --local user.email  "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "style: auto format with clang-format"
          git push
        else
          echo "No changes to commit"
        fi
